language: php
php:
- 7.1
- 7.2

cache:
  directories:
  - "$HOME/.composer/cache"

before_script:
- travis_retry composer self-update

install:
- travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpstan analyse -c phpstan.neon -l 7 src/
  - vendor/bin/tester tests/